language: node_js
node_js:
  - "5.7.0"
before_script:
  - "npm install"
  - "tsd reinstall"
after_success:
  - "jake upload"
sudo: false
notifications:
  email:
    - touchdevelop-build@microsoft.com
cache:
  directories:
    - node_modules
    - typings
    - webapp/node_modules
    - webapp/typings

