language: node_js
node_js:
  - "5.7.0"
before_script:
  - "npm install"
  - "tsd reinstall"
sudo: false
notifications:
  email:
    - touchdevelop-build@microsoft.com
  slack: pxt-team:dNxkje2gg4MgRxX1imoyXWLD
    on_success: always
    on_failure: always
cache:
  directories:
    - node_modules
    - typings

