site_name: yelm
site_description: Typescript compiler for micro:bit.
pages:
- Home: index.rst
theme: readthedocs
repo_url: https://github.com/microsoft/yelm/
copyright: Copyright &copy; 2016 Microsoft
