site_name: KindScript
site_description: A Kinder JavaScript Experience.
pages:
- Home: index.md
theme: readthedocs
repo_url: https://github.com/microsoft/kindscript/
copyright: Copyright &copy; 2016 Microsoft
